### ISSUE TITLE
Path error / files not converted

### ISSUE THREAD

**Issue by GenerationFallout** [octfx/mediawiki-extension-WebP#1]
Hello,

Thank you for this extension!

With us it does not seem to work, during the installation, the / images directory is missing when it is displayed:

![1](https://user-images.githubusercontent.com/68496923/121229255-02093080-c88e-11eb-8d92-b739d6e1d37f.png)

The upload also seems to hang due to this error:

![Capture](https://user-images.githubusercontent.com/68496923/121229336-16e5c400-c88e-11eb-8540-9c957dab48ec.PNG)

And the cron task which should convert the files therefore does not produce them and does not raise an error:

![image](https://user-images.githubusercontent.com/68496923/121229547-64623100-c88e-11eb-855f-6abcb794b49e.png)
![image](https://user-images.githubusercontent.com/68496923/121229606-75ab3d80-c88e-11eb-8b2b-c8a5757903fe.png)

Why not use the mediawiki path parameters directly?

Thanking you once again for your work :)

**Comment by octfx** [comment]
I'll try to test this against MediaWiki 1.36 later :)

Did you add the required `$wgLocalFileRepo` setting?
And what is the value of `$wgUploadDirectory`?

**Comment by GenerationFallout** [comment]
$wgLocalFileRepo is ok :)
$wgUploadDirectory is not defined in our LocalSettings.php :)

**Comment by GenerationFallout** [comment]
Ok, after having defined this one the problem is partially solved:
https://fallout-wiki.com/Accueil
By adding two variables that we didn't have:
$wgUploadDirectory= "{$IP}/images";
$wgThumbnailScriptPath = "$wgScriptPath/thumb.php";

**Comment by octfx** [comment]
The latest patch should enable generating thumbs through thumb.php

**Comment by octfx** [comment]
I've pushed a fix that should enable webp generation through `thumb.php`.

But full disclosure: It is kind of hacked together... This extension isn't fully tested and was created to check if it was possible to generate webp files from existing images.
So please keep in mind that this extension can possibly break things

**Comment by GenerationFallout** [comment]
I have upgraded the extension with us and it works fine :)

Except with MSupload with an error -200, I will wait to push a little further before confirming :)
