### ISSUE TITLE
Not displaying converted images in the File: page

### ISSUE THREAD

**Issue by cooperdk** [octfx/mediawiki-extension-WebP#11]
I have a new issue where I can confirm that the images are indeed converted thru the maintenance script, but still not shown in the File interface. I did restart Apache, PHP-FPM and Memcached.

![image](https://user-images.githubusercontent.com/564150/177224456-15c86f9d-991f-488f-852e-e66eadc69324.png)

The interface refers to the file in 120px format for the thumbnail:

<img alt="Miniature af versionen fra 15. jun. 2022, 19:53" src="/images/thumb/webp/d/dd/Elisha_Cuthbert.jpg/120px-Elisha_Cuthbert.webp" decoding="async" width="85" height="120" data-file-width="300" data-file-height="421">

And the full-size image for the image itself:

<a href="https://spademanns.dk/images/webp/d/dd/Elisha_Cuthbert.webp" class="mw-mmv-view-expanded mw-ui-button"><span class="mw-ui-icon mw-ui-icon-before"><span>Open in Media Viewer</span></span></a>

Both these files are present in the file system.

![image](https://user-images.githubusercontent.com/564150/177224584-52ac4f3d-931a-4b7d-9436-8987a7269d86.png)
![image](https://user-images.githubusercontent.com/564150/177224595-04215d55-3272-4f5e-8487-eb79bf7932bd.png)

However, the file is not resized to 120px as defined in the LocalSettings.php file:

![image](https://user-images.githubusercontent.com/564150/177224638-37cfee19-6f47-4bde-bd53-1397e19f79a4.png)

Looking at the img tag for the thumbnail, it sets the thumbnail to the correct height and width, but it mistakenly names the file by thumbnail HEIGHT, not WIDTH. Since the file is saved as 85px-Elisha_Cuthbert.jpg, something goes wrong somewhere in the img size definitions.

Also, the extension does not auto-convert thumbnails/images on the fly when visiting a page with an image that has not been converted, even though MediaWiki does this with the WebP extension disabled. My htaccess is setup correctly to do this.

**Comment by cooperdk** [comment]
FYI, I just tried to re-create the example thumbnails. This is on a new server.
In this case, it made two other sizes, 320px and 800px (this is an image which is 300x421px in size so it makes NO sense that it makes an 800px version).
The 320px version is 320x449 and the 800px version is ... 800x1123 and is visibly enlarged.

The thumbnails still don't show up on the file page.

I do not understand that your script resizes to bigger proportions than the original.
The original jpeg thumbs are 85 (85x119), 200 (200x281) and 220 (220x312) px.

Why doesn't the system just resize those thumbs instead of re-inventing the wheel, using the original image makes it take longer to resize.

This extension is clearly broken or at the very least, practically unusable at this point.

**Comment by octfx** [comment]
I'm sorry that you are having such a bad experience with this.  
The extension was only somewhat tested on MW `1.35` with [thumb.php](https://www.mediawiki.org/wiki/Manual:Thumb.php) active.

As written in the first sentence in the readme, the extension is still experimental.

MediaWiki does not support generating ans serving alternate files transparently, so everything this extension does has to be done manually using somewhat low-level file operations.

While I'd love to get this extension in a working state, I currently have no capacity to fix it. So pull requests / forks are more than welcome.

**Comment by octfx** [comment]
> Also, the extension does not auto-convert thumbnails/images on the fly when visiting a page with an image that has not been converted, even though MediaWiki does this with the WebP extension disabled. My htaccess is setup correctly to do this.

Just noticed: Setting `$wgWebPConvertInJobQueue` runs every conversion through the job queue, so nothing is generated on the fly.

You may set it to false, to force creation on page view.

Also: Current develop was tested locally with MW1.39 and the basics should work.
