### ISSUE TITLE
[Evolution] - Download/access the original format

### ISSUE THREAD

**Issue by GenerationFallout** [octfx/mediawiki-extension-WebP#16]
Hello,

With the Webp installation, the "original file" option redirects to the Webp version of the image if it has been converted: 

https://fallout-wiki.com/Fichier:Logo_pl.png

Is it possible to add an option "original format" (or equivalent) to avoid having to modify the url manually ? 

Sincerely,

Kils

**Comment by octfx** [comment]
This is fixed in current develop :)
