### ISSUE TITLE
Fatal error on MW 1.40+ versions

### ISSUE THREAD

**Issue by Aeywoo** [octfx/mediawiki-extension-WebP#21]
I recently set up a brand-new wiki on MediaWiki 1.41.2, I installed WebP alongside my other extensions and it threw out this error when attempting to generate a thumbnail for the file I uploaded. Here is the following error backtrace:

[4361be910840535188d0f3e9] /w/File:Verified.svg TypeError: explode(): Argument #2 ($string) must be of type string, bool given

Backtrace:

from /var/www/html/public_html/extensions/WebP/includes/Hooks/ThumbnailHooks.php(131)
`#0` /var/www/html/public_html/extensions/WebP/includes/Hooks/ThumbnailHooks.php(131): explode()
`#1` /var/www/html/public_html/includes/HookContainer/HookContainer.php(161): MediaWiki\Extension\WebP\Hooks\ThumbnailHooks->onPictureHtmlSupportBeforeProduceHtml()
`#2` /var/www/html/public_html/extensions/PictureHtmlSupport/includes/ThumbnailImage.php(221): MediaWiki\HookContainer\HookContainer->run()
`#3` /var/www/html/public_html/includes/page/ImagePage.php(482): ThumbnailImage->toHtml()
`#4` /var/www/html/public_html/includes/page/ImagePage.php(144): ImagePage->openShowImage()
`#5` /var/www/html/public_html/includes/actions/ViewAction.php(78): ImagePage->view()
`#6` /var/www/html/public_html/includes/MediaWiki.php(583): ViewAction->show()
`#7` /var/www/html/public_html/includes/MediaWiki.php(363): MediaWiki->performAction()
`#8` /var/www/html/public_html/includes/MediaWiki.php(960): MediaWiki->performRequest()
`#9` /var/www/html/public_html/includes/MediaWiki.php(613): MediaWiki->main()
`#10` /var/www/html/public_html/index.php(50): MediaWiki->run()
`#11` /var/www/html/public_html/index.php(46): wfIndexMain()
`#12` {main}

This error stems from this line in /includes/Hooks/ThumbnailHooks.php on line 131 (as stated in the backtrace):
`$filepath = explode( $hash, $thumbnail->getStoragePath() );`

Would love some help in fixing this issue so I can continue using this extension in newer versions of MediaWiki, thanks for the great extension!

**Comment by octfx** [comment]
This should now be fixed
Would you mind testing the current develop branch?

**Comment by Aeywoo** [comment]
It's not generating thumbnails still for some reason.

**Comment by octfx** [comment]
Is your job queue fully working?
Are there any webp files in `images/webp` and `images/thumb/webp`?

You could test showing an image with some odd dimensions like `[[FIle:File.png|321px]]`  and see if a thumb with that dimension is generated.

**Comment by Aeywoo** [comment]
I'm using an Akamai Linode S3 compatible bucket, there is an `images/webp` folder, but it only has one entry for a file that isn't displaying any thumbnail on its file page. And there is a job queue setup but there are no active jobs right now. File in question: https://quantumscience.wiki/w/File:Kerman_Update_Header.png
