### ISSUE TITLE
Some images are not served in webP

### ISSUE THREAD

**Issue by GenerationFallout** [octfx/mediawiki-extension-WebP#3]
Hello,

I notice that some images are not served in WEBP on compatible browsers: https://fallout-wiki.com/

A concrete example on this page :

https://fallout-wiki.com/Alli%C3%A9_:_Crash_a%C3%A9rien
The WEBP version exists (36,864 bytes) as well as the jpg version (53,248 bytes) but it is the jpg version (heavier) which is served rather than the WEBP

Attached are the two images from the FTP :

[jpg and webp.zip](https://github.com/octfx/mediawiki-extension-WebP/files/6621953/jpg.and.webp.zip)

Is there a specific rule that would explain this phenomenon?

Thank

Kims

**Comment by octfx** [comment]
The extension checks if the browser supports webp images.
This check can be disabled by setting `$wgWebPCheckAcceptHeader = false`;

**Comment by GenerationFallout** [comment]
The browser seems to be recognized for some images but not for others.
All the images on the wiki have however been converted via the taskjob
On my index page, for example, some are in WEBP, others on their initial formats.
On the other page (https://fallout-wiki.com/Alli%C3%A9_:_Crash_a%C3%A9rien) the WEBP image exists but only the jpg version is served :)
Thank :)

**Comment by octfx** [comment]
The image link is a little missleading
While `https://fallout-wiki.com/thumb.php?f=Alli%C3%A9_-_Crash_a%C3%A9rien.jpg&width=265` says it is a `jpg` file, in reality the `webp` thumb is returned.

You can validate this by downloading the file and opening it in a text editor, the first line should read `... WEBPVP8 ...`.

The filname in the url just tells MediaWiki which file to use, to generate the thumbnail from :)

**Comment by GenerationFallout** [comment]
Ah, exact !!!

![image](https://user-images.githubusercontent.com/68496923/121330889-b0f14f00-c916-11eb-8731-e05b41708dcc.png)

I was not suspicious, sorry :)
So everything is working fine!
Thank you for your top job :)
