### ISSUE TITLE
 Error with gif

### ISSUE THREAD

**Issue by GenerationFallout** [octfx/mediawiki-extension-WebP#4]
Hello,

It seems that the extension is causing display problems with the gif: https://fallout-wiki.com/%C3%89motic%C3%B4ne_de_Fallout_76

The extension disabled, they work :)

Thank you :)

**Comment by GenerationFallout** [comment]
![image](https://user-images.githubusercontent.com/68496923/121345968-cb7ef480-c925-11eb-95d0-40b1478a74c2.png)

**Comment by GenerationFallout** [comment]
Up :)

**Comment by octfx** [comment]
Oh sorry, I've missed your post!
I'll try to get back to this in about a week, time is short right now, sorry :/

**Comment by GenerationFallout** [comment]
It's okay, I thought so :D
Thanks, that's all we need to make it perfect!

**Comment by octfx** [comment]
Can you test the current develop branch?  
Local tests with Gifs were successful!

**Comment by octfx** [comment]
Can you test the current develop branch?  
Local tests with gifs were successful!

**Comment by GenerationFallout** [comment]
Hello,
Sorry, I didn't see your message, the current branch totally breaks the images: 
![image](https://user-images.githubusercontent.com/68496923/124653791-041adb00-de9e-11eb-8ffa-ceb35760f858.png)
And the gifs are no longer displayed: 
![image](https://user-images.githubusercontent.com/68496923/124653857-1a289b80-de9e-11eb-8964-7d695febee67.png)
Thank :)

**Comment by octfx** [comment]
Can you remove the `$wgLocalFileRepo` setting from LocalSettings and try again?

**Comment by GenerationFallout** [comment]
Ah yes ! 
I deleted the old lines: 
```
$wgLocalFileRepo = [
    'class' => \MediaWiki\Extension\WebP\Repo\LocalWebPFileRepo::class,
    'name' => 'local',
    'directory' => $wgUploadDirectory,
    'scriptDirUrl' => $wgScriptPath,
    'url' => $wgUploadBaseUrl ? $wgUploadBaseUrl . $wgUploadPath : $wgUploadPath,
    'hashLevels' => $wgHashedUploadDirectory ? 2 : 0,
    'thumbScriptUrl' => $wgThumbnailScriptPath,
    'transformVia404' => false,
    'deletedDir' => "{$wgUploadDirectory}/deleted",
    'deletedHashLevels' => $wgHashedUploadDirectory ? 3 : 0
```
];
And left only : 
```
wfLoadExtension( 'WebP' );

$wgWebPCompressionQuality = 50;
$wgWebPFilterStrength = 50;
$wgWebPAutoFilter = true;
$wgWebPConvertInJobQueue = true;
$wgWebPEnableConvertOnUpload = true;
$wgWebPEnableConvertOnTransform = true;
```

And everything works :)

**Comment by octfx** [comment]
Perfect :)

**Comment by GenerationFallout** [comment]
I spoke too quickly, when I use the development version without $wgLocalFileRepo['class'] = LocalWebPFileRepo::class; :


```
MediaWiki internal error.

Original exception: [YOSyoEslFM4Hc-lUVjWBfwAAAAo] /Accueil MWException: FileRepo requires an array of options having both 'name' and 'backend' keys.

Backtrace:
from /var/www/vhosts/fallout-wiki.com/httpdocs/includes/filerepo/FileRepo.php(170)
#0 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/filerepo/LocalRepo.php(57): FileRepo->__construct()
#1 /var/www/vhosts/fallout-wiki.com/httpdocs/extensions/WebP/includes/Repo/LocalWebPFileRepo.php(33): LocalRepo->__construct()
#2 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/filerepo/RepoGroup.php(422): MediaWiki\Extension\WebP\Repo\LocalWebPFileRepo->__construct()
#3 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/filerepo/RepoGroup.php(405): RepoGroup->newRepo()
#4 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/filerepo/RepoGroup.php(132): RepoGroup->initialiseRepos()
#5 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/BadFileLookup.php(71): RepoGroup->findFile()
#6 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/parser/Parser.php(2616): MediaWiki\BadFileLookup->isBadFile()
#7 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/parser/Parser.php(2379): Parser->handleInternalLinks2()
#8 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/parser/Parser.php(1578): Parser->handleInternalLinks()
#9 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/parser/Parser.php(639): Parser->internalParse()
#10 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/content/WikitextContent.php(375): Parser->parse()
#11 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/content/AbstractContent.php(591): WikitextContent->fillParserOutput()
#12 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/Revision/RenderedRevision.php(263): AbstractContent->getParserOutput()
#13 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/Revision/RenderedRevision.php(235): MediaWiki\Revision\RenderedRevision->getSlotParserOutputUncached()
#14 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/Revision/RevisionRenderer.php(217): MediaWiki\Revision\RenderedRevision->getSlotParserOutput()
#15 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/Revision/RevisionRenderer.php(154): MediaWiki\Revision\RevisionRenderer->combineSlotOutput()
#16 [internal function]: MediaWiki\Revision\RevisionRenderer->MediaWiki\Revision\{closure}()
#17 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/Revision/RenderedRevision.php(197): call_user_func()
#18 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/poolcounter/PoolWorkArticleView.php(137): MediaWiki\Revision\RenderedRevision->getRevisionParserOutput()
#19 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/poolcounter/PoolCounterWork.php(162): PoolWorkArticleView->doWork()
#20 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/page/ParserOutputAccess.php(281): PoolCounterWork->execute()
#21 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/page/Article.php(746): MediaWiki\Page\ParserOutputAccess->getParserOutput()
#22 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/page/Article.php(561): Article->generateContentOutput()
#23 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/actions/ViewAction.php(74): Article->view()
#24 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/MediaWiki.php(531): ViewAction->show()
#25 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/MediaWiki.php(315): MediaWiki->performAction()
#26 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/MediaWiki.php(913): MediaWiki->performRequest()
#27 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/MediaWiki.php(546): MediaWiki->main()
#28 /var/www/vhosts/fallout-wiki.com/httpdocs/index.php(53): MediaWiki->run()
#29 /var/www/vhosts/fallout-wiki.com/httpdocs/index.php(46): wfIndexMain()
#30 {main}

Exception caught inside exception handler: [YOSyoEslFM4Hc-lUVjWBfwAAAAo] /Accueil Error: Call to a member function findFile() on null
Backtrace:
from /var/www/vhosts/fallout-wiki.com/httpdocs/includes/filerepo/RepoGroup.php(156)
#0 /var/www/vhosts/fallout-wiki.com/httpdocs/extensions/PageImages/includes/PageImages.php(116): RepoGroup->findFile()
#1 /var/www/vhosts/fallout-wiki.com/httpdocs/extensions/PageImages/includes/PageImages.php(252): PageImages\PageImages::getPageImage()
#2 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/HookContainer/HookContainer.php(338): PageImages\PageImages::onBeforePageDisplay()
#3 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/HookContainer/HookContainer.php(137): MediaWiki\HookContainer\HookContainer->callLegacyHook()
#4 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/HookContainer/HookRunner.php(1000): MediaWiki\HookContainer\HookContainer->run()
#5 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/OutputPage.php(2629): MediaWiki\HookContainer\HookRunner->onBeforePageDisplay()
#6 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/exception/MWException.php(193): OutputPage->output()
#7 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/exception/MWException.php(231): MWException->reportHTML()
#8 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/exception/MWExceptionHandler.php(104): MWException->report()
#9 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/exception/MWExceptionHandler.php(185): MWExceptionHandler::report()
#10 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/MediaWiki.php(565): MWExceptionHandler::handleException()
#11 /var/www/vhosts/fallout-wiki.com/httpdocs/index.php(53): MediaWiki->run()
#12 /var/www/vhosts/fallout-wiki.com/httpdocs/index.php(46): wfIndexMain()
#13 {main}
```
And without the images are simply no longer served in WEBP.
Same for the master version

So I use this version with my old settings: 
[WebP.zip](https://github.com/octfx/mediawiki-extension-WebP/files/6772490/WebP.zip)

**Comment by octfx** [comment]
Hmm, seems like the extension writes to `wgLocalFileRepo` before `Setup.php` is run (which should not be possible?).

I've added both `name` and `backend` keys to fix the error, could you test the current develop again?

**Comment by GenerationFallout** [comment]
A new error is now generated:

```
[YOS8S@Z71fIQUM-5FSUCaQAAAAI] /Appareil_photo_ProSnap_Deluxe TypeError: pathinfo() expects parameter 1 to be string, bool given

Backtrace:

from /var/www/vhosts/fallout-wiki.com/httpdocs/extensions/WebP/includes/Hooks/ThumbnailHooks.php(130)
#0 /var/www/vhosts/fallout-wiki.com/httpdocs/extensions/WebP/includes/Hooks/ThumbnailHooks.php(130): pathinfo()
#1 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/HookContainer/HookContainer.php(160): MediaWiki\Extension\WebP\Hooks\ThumbnailHooks->onThumbnailBeforeProduceHTML()
#2 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/HookContainer/HookRunner.php(3944): MediaWiki\HookContainer\HookContainer->run()
#3 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/media/ThumbnailImage.php(214): MediaWiki\HookContainer\HookRunner->onThumbnailBeforeProduceHTML()
#4 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/Linker.php(432): ThumbnailImage->toHtml()
#5 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/parser/Parser.php(5428): Linker::makeImageLink()
#6 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/parser/Parser.php(2632): Parser->makeImage()
#7 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/parser/Parser.php(2379): Parser->handleInternalLinks2()
#8 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/parser/Parser.php(1578): Parser->handleInternalLinks()
#9 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/parser/Parser.php(639): Parser->internalParse()
#10 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/content/WikitextContent.php(375): Parser->parse()
#11 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/content/AbstractContent.php(591): WikitextContent->fillParserOutput()
#12 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/Revision/RenderedRevision.php(263): AbstractContent->getParserOutput()
#13 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/Revision/RenderedRevision.php(235): MediaWiki\Revision\RenderedRevision->getSlotParserOutputUncached()
#14 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/Revision/RevisionRenderer.php(217): MediaWiki\Revision\RenderedRevision->getSlotParserOutput()
#15 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/Revision/RevisionRenderer.php(154): MediaWiki\Revision\RevisionRenderer->combineSlotOutput()
#16 [internal function]: MediaWiki\Revision\RevisionRenderer->MediaWiki\Revision\{closure}()
#17 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/Revision/RenderedRevision.php(197): call_user_func()
#18 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/poolcounter/PoolWorkArticleView.php(137): MediaWiki\Revision\RenderedRevision->getRevisionParserOutput()
#19 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/poolcounter/PoolCounterWork.php(162): PoolWorkArticleView->doWork()
#20 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/page/ParserOutputAccess.php(281): PoolCounterWork->execute()
#21 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/page/Article.php(746): MediaWiki\Page\ParserOutputAccess->getParserOutput()
#22 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/page/Article.php(561): Article->generateContentOutput()
#23 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/actions/ViewAction.php(74): Article->view()
#24 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/MediaWiki.php(531): ViewAction->show()
#25 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/MediaWiki.php(315): MediaWiki->performAction()
#26 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/MediaWiki.php(913): MediaWiki->performRequest()
#27 /var/www/vhosts/fallout-wiki.com/httpdocs/includes/MediaWiki.php(546): MediaWiki->main()
#28 /var/www/vhosts/fallout-wiki.com/httpdocs/index.php(53): MediaWiki->run()
#29 /var/www/vhosts/fallout-wiki.com/httpdocs/index.php(46): wfIndexMain()
#30 {main}
```

**Comment by octfx** [comment]
Updated in current develop

Btw what is your value of `$wgThumbnailScriptPath`?
If it is set to `false` could you set it as described here: https://www.mediawiki.org/wiki/Manual:Thumb.php#Scripted_transform ?

**Comment by GenerationFallout** [comment]
Ours is defined this way: 
$wgThumbnailScriptPath = "$wgScriptPath/thumb.php";

**Comment by GenerationFallout** [comment]
With the development version, no more images are displayed: 

![image](https://user-images.githubusercontent.com/68496923/124664487-d046b200-deab-11eb-90cc-db599eeae506.png)

**Comment by GenerationFallout** [comment]
![image](https://user-images.githubusercontent.com/68496923/124664578-f2403480-deab-11eb-9f44-1bcc6e5628c2.png)
![image](https://user-images.githubusercontent.com/68496923/124664600-fa986f80-deab-11eb-891b-f220bbaf0e83.png)

**Comment by octfx** [comment]
Somehow the extension is dropping the `images` part from the url, I'll investigate

**Comment by GenerationFallout** [comment]
In this case it retrieves the image from : 
https://fallout-wiki.com/8/86/Icon_Fo76_Cryptid_quest.png
Instead of 
https://fallout-wiki.com/images/8/86/Icon_Fo76_Cryptid_quest.png

**Comment by octfx** [comment]
So, the main error was trying to transform thumbnails that are bigger than the source image.

Could you check the current develop branch @GenerationFallout ?

**Comment by GenerationFallout** [comment]
Hello,

I just tried, same problem 

Kims :)

**Comment by octfx** [comment]
Hm strange, there are some gifs visible 🤔
I'll check some gifs from your site locally

**Comment by octfx** [comment]
I can't reproduce the error..
I've tried the following gifs:
![Centaure_anime](https://user-images.githubusercontent.com/6594492/125139116-3e8bae80-e110-11eb-8720-a2456f7e7e96.gif)
![Heart1](https://user-images.githubusercontent.com/6594492/125139118-3f244500-e110-11eb-81b3-430462bc2261.gif)

Both MW 1.35 and 1.36 show a thumbnailed version of the uploaded gif using WebP (0088eaf):
![iridium_IP91IWzngB](https://user-images.githubusercontent.com/6594492/125139274-890d2b00-e110-11eb-8177-6de27378b7c2.png)

The only thing left I think would be to setup a [Log file](https://www.mediawiki.org/wiki/Manual:How_to_debug#Setting_up_a_debug_log_file) visit a few pages with gifs and sending me the output (although you'd have to check for sensible data in that first).

**Comment by GenerationFallout** [comment]
Yes I don't understand, in all cases the gif files are not in the webp directory but some are served correctly and others not...

![image](https://user-images.githubusercontent.com/68496923/125140524-00dc5500-e113-11eb-838e-6ab4f6164648.png)

**Comment by GenerationFallout** [comment]
I have the impression that it tries to force the display of gif in webp format when they are not present in the webp directory, is there not an exclusion rule that would not work?

**Comment by octfx** [comment]
The extension checks if a file can be converted to webp by checking the mine type
image/gif is set to be skipped, so the extension shouldn't interact with this file 

I'll create a debug version later, hopefully will give some insight into why it's not working

**Comment by octfx** [comment]
> Yes I don't understand, in all cases the gif files are not in the webp directory but some are served correctly and others not...
> 
> ![image](https://user-images.githubusercontent.com/68496923/125140524-00dc5500-e113-11eb-838e-6ab4f6164648.png)

Although that does not look correct 
The file extension should not change to webp

**Comment by octfx** [comment]
Ok so, I've added a branch containing debug statements: https://github.com/octfx/mediawiki-extension-WebP/tree/debug_logs
You'd need to add the following code to your LocalSettings (and maybe change the paths):
```php

$wgDebugLogGroups = [
	'WebP' => '/tmp/webp.log',
];

$wgDebugLogFile = "/tmp/debug.log";
``` 

After this is active for a few minutes (and pages with gif errors were visited) I'd need both files containing the log data.
You can upload those files privately to my cloud at https://cloud.octofox.de/s/upload

**Comment by GenerationFallout** [comment]
Hello,

I just sent you the logs with the debug version and a debug.log with my current version and setting :)

**Comment by octfx** [comment]
Perfect, I'll get back to you when I've analyzed them! :)

**Comment by octfx** [comment]
So it seems like the local file backend name was not set
Hopefully the current develop branch fixes this

**Comment by GenerationFallout** [comment]
The problem persists, the image directory is still not recognized, I just sent you long :)

**Comment by octfx** [comment]
So the logs show some `open_basedir` restrictions, as the extension tries to load thumbnails from `/thumb/webp...`   
This may be related to issue 5

I'll try to investigate further, but can't guarantee any results in the next few days/weeks :/

**Comment by GenerationFallout** [comment]
Hi, 

No worries! If it helps, I see similar behavior on this page: https://fallout-wiki.com/%C3%89v%C3%A8nement_:_Un_probl%C3%A8me_colossal

The downloaded image is : FO76_Un_problème_colossal.gif.webp

However the code is well : 

`<td class="va-infobox-mainimage-image" style=""><a href="/Fichier:FO76_Un_probl%C3%A8me_colossal.gif" class="image"><img alt="FO76 Un problème colossal.gif" src="/thumb.php?f=FO76_Un_probl%C3%A8me_colossal.gif&amp;width=320" decoding="async" width="320" height="186" srcset="/thumb.php?f=FO76_Un_probl%C3%A8me_colossal.gif&amp;width=480 1.5x, /images/c/c0/FO76_Un_probl%C3%A8me_colossal.gif 2x" data-file-width="535" data-file-height="311"></a></td>`

Kims

**Comment by GenerationFallout** [comment]
Et si je change le code pour : 

`<img alt="FO76 Un problème colossal.gif" src=" /images/c/c0/FO76_Un_probl%C3%A8me_colossal.gif" decoding="async" width="320" height="186" srcset="/thumb.php?f=FO76_Un_probl%C3%A8me_colossal.gif&amp;width=480 1.5x, /images/c/c0/FO76_Un_probl%C3%A8me_colossal.gif 2x" data-file-width="535" data-file-height="311">`

it works :)

**Comment by GenerationFallout** [comment]
Hello,

We have switched to mediawiki 1.37.0-wmf.22 and Wepb is working, only this gif problem remains.
Version 8 of php on a development environment does not seem to be a problem either.

Kims

**Comment by GenerationFallout** [comment]
Bug fixed with the last maj :)

**Comment by octfx** [comment]
Oh man I totally forgot about this issue, sorry!

Glad that everything is working as intended 😊
