### ISSUE TITLE
Extension breaking thumbnails

### ISSUE THREAD

**Issue by Universal-Omega** [octfx/mediawiki-extension-WebP#5]
The extension is loading images as https://static.miraheze.org/test3wiki/9/9e/WebP_test.webp whereas it should be loading them as https://static.miraheze.org/test3wiki/webp/9/9e/WebP_test.webp but isn't.

https://test3.miraheze.org/wiki/File:WebP_test.png for example file description page.

Ping: @octfx

**Comment by octfx** [comment]
I'll look into it

**Comment by Universal-Omega** [comment]
> I'll look into it

Thank you!

**Comment by octfx** [comment]
I can't confirm the issue using a local 1.35.2 installation. :/
I suppose you are not using a local file repo?

Can you add more info about how the upload directory is setup and which config values you are using?
My guess is that the issue has something todo with the content being hosted on a separate domain.

**Comment by Universal-Omega** [comment]
We are using 1.36.0.
https://github.com/miraheze/mw-config/blob/990546a/LocalSettings.php#L4729-L4730 is the values of wgUploadPath and wgUploadDirectory
https://github.com/miraheze/mw-config/pull/3982 is the config we have set for the extension which is pulled to our testing wiki.

Our configuration can be quite complex so if you need further explanation or details I will gladly provide them. Thank you!

**Comment by octfx** [comment]
Many thanks. I'll try to create a running environment using the config vars and re-check the extension!

**Comment by Universal-Omega** [comment]
Images display on the develop branch, but only their png images, not webp versions. Just thought I'd mention that.

**Comment by octfx** [comment]
With or without using thumb.php?

**Comment by octfx** [comment]
The develop branch doesn't require setting `$wgLocalFileRepo`.
But I haven't looked into the wrong path issue yet

**Comment by Universal-Omega** [comment]
> The develop branch doesn't require setting `$wgLocalFileRepo`.
> But I haven't looked into the wrong path issue yet

OK, thank you for looking into this. I do hope to have it resolved so that we may install the extension.

**Comment by octfx** [comment]
I think I've found a possible error.
Could you try the current develop branch?

**Comment by Universal-Omega** [comment]
> I think I've found a possible error.
> Could you try the current develop branch?

The develop branch does not break thumbnails, but webp images are not shown at all.

**Comment by octfx** [comment]
Can you check if for https://test3.miraheze.org/wiki/File:WebP_test.png the following thumbs exist?
- `thumb/webp/9/9e/WebP_test.png/120px-WebP_test.webp`
- `thumb/webp/9/9e/WebP_test.png/800px-WebP_test.webp`
- `thumb/webp/9/9e/WebP_test.png/1200px-WebP_test.webp`

When `$wgThumbnailScriptPath` is not set, webp thumbs will only be created if the corresponding jpg, png thumb is created through MW

Alternatively you could run the maintenance script like  
`php ConvertImages.php --only-thumbs --thumb-sizes 120,800,1200 --title-prefix=WebP_test --overwrite`

That should create the needed webp thumbs for the file in question

**Comment by Universal-Omega** [comment]
> Can you check if for https://test3.miraheze.org/wiki/File:WebP_test.png the following thumbs exist?
> 
> * `thumb/webp/9/9e/WebP_test.png/120px-WebP_test.webp`
> * `thumb/webp/9/9e/WebP_test.png/800px-WebP_test.webp`
> * `thumb/webp/9/9e/WebP_test.png/1200px-WebP_test.webp`
> 
> When `$wgThumbnailScriptPath` is not set, webp thumbs will only be created if the corresponding jpg, png thumb is created through MW
> 
> Alternatively you could run the maintenance script like
> `php ConvertImages.php --only-thumbs --thumb-sizes 120,800,1200 --title-prefix=WebP_test --overwrite`
> 
> That should create the needed webp thumbs for the file in question

Yes, those files do exist:
https://static.miraheze.org/test3wiki/webp/9/9e/WebP_test.webp

https://static.miraheze.org/test3wiki/thumb/webp/9/9e/WebP_test.png/120px-WebP_test.webp
https://static.miraheze.org/test3wiki/thumb/webp/9/9e/WebP_test.png/800px-WebP_test.webp
https://static.miraheze.org/test3wiki/thumb/webp/9/9e/WebP_test.png/1200px-WebP_test.webp

**Comment by octfx** [comment]
Hm there seems to be a fundamental path problem somewhere, this is affecting the gif issue also.

I'll have to re-check the method calls. Sadly I'm a little short on free time, so this may take some days... :/

**Comment by octfx** [comment]
I've checked the paths for thumbs not using `thumb.php` and found two path errors while generating the thumb urls.  

Further I've added debug statements to the develop branch, so if it still fails with the current commit, maybe you could provide them to me.

**Comment by Universal-Omega** [comment]
The develop branch does now seem to work. Thank you! Please let me know when this is live on master so that we can install it.

**Comment by octfx** [comment]
@Universal-Omega better late than nerver I guess :s

I've released v1.0.0 just now. Fixed some more bugs and can report that it run stable this last year on my site!
