### ISSUE TITLE
Problem with image scaling

### ISSUE THREAD

**Issue by GenerationFallout** [octfx/mediawiki-extension-WebP#7]
Hello,

On some galleries, there seems to be a scaling problem if the image is smaller than the gallery in which it is integrated: 

https://fallout-wiki.com/Grand_RIEN

![image](https://user-images.githubusercontent.com/68496923/150508058-0b05ef9e-baa6-48c6-902b-5d269ab97e0a.png)

The code in question: 
![image](https://user-images.githubusercontent.com/68496923/150508252-4a9ca23f-42f5-4c2e-8d10-55f7002bc3ee.png)
And the rendering : 
![image](https://user-images.githubusercontent.com/68496923/150508475-e67265f1-772c-4d0a-a07e-321365de97ee.png)

And if we remove the "widths=250" everything is normal again:
![image](https://user-images.githubusercontent.com/68496923/150508830-38b6d5d3-1203-4b18-b55e-2cd6a1f8fec9.png)
![image](https://user-images.githubusercontent.com/68496923/150508901-93b1731a-cec9-4e39-a53e-a96681589fb8.png)

Sincerely,

Kims

**Comment by octfx** [comment]
I can tell you why this is happening, but I don't have an idea how to really fix this.

The file https://fallout-wiki.com/Fichier:FNVOWB_Grand_RIEN_Panorama.png is `210px` wide but the gallery tries to resize the image to `250px`.  
This would normally cause an error with `thumb.php` because thumbnails can't be bigger than the original image.  
The extension detects this and sets the width to the size of the image (in this case `210px`). Thats why that image is bigger than all others.

An intermediate (dirty) fix would be to upload a rescaled version (250x250px) of the image,

**Comment by GenerationFallout** [comment]
Hello,

Without the extension, these images are displayed correctly without error in the relevant image galleries :)

Kims

**Comment by octfx** [comment]
Could you try the latest develop commit?

**Comment by GenerationFallout** [comment]
It seems to work on the development version once the cache is cleared :)

**Comment by GenerationFallout** [comment]
Hello, it seems that it also affects other pages with stretched images with the extension : 

Avec :
![image](https://user-images.githubusercontent.com/68496923/150728157-be8c80fc-e693-4d2c-84b5-3091176b32aa.png)
Sans :
![image](https://user-images.githubusercontent.com/68496923/150728139-ff547ce3-e59d-4af9-b3c5-2fd45c845f66.png)

An example on the next page: https://fallout-wiki.com/Armures_et_v%C3%AAtements_de_Fallout#Liste_des_armures

Kims

**Comment by octfx** [comment]
Latest develop commit should address this error :)

**Comment by GenerationFallout** [comment]
Hello,

Thank you, the latest development version does indeed solve this error.
There is still a small problem for us on some small images:  
https://fallout-wiki.com/Accueil
https://fallout-wiki.com/Fichier:Logo_Fallout2.png
These seem to display badly since the last maj of the development version, maybe due to their dementions? 
Cordialy,
Kims

**Comment by octfx** [comment]
I think it has something to do with the image dimensions.
I've added a patch and tried one of the files locally, seems to work. Could you try the latest commit again?

**Comment by GenerationFallout** [comment]
Hello,

I just applied the patch, no change on my side :/

Kims

**Comment by octfx** [comment]
Hm, I've tested `Logo Fallout2.png` using a local MW 1.38.0-wmf.18 installation. But I can't reproduce the error.
![msedge_HWrVev8yYX](https://user-images.githubusercontent.com/6594492/150961656-b54d7ed3-a186-431d-a1c2-c54e8db7af93.png)

I don't really know where to go from here. Maybe you could enable debug logs.

**Comment by GenerationFallout** [comment]
Here is the error I get with the latest development version: 
https://fallout-wiki.com/thumb.php?f=Logo_Fallout2.png&width=90
File not found
Although this PHP script (/thumb.php) exists, the file requested for output (mwstore://local-backend/local-thumb/webp/9/98/Logo_Fallout

What log files do you need?

Note that on the master, these images are displayed normally  (but distorted ^^) :)

Kims

**Comment by octfx** [comment]
If you could try the latest develop with:
```php
$wgDebugLogGroups = [
	'WebP' => '<path to log>',
];
```
You can share the debug file with me using this link: http://cloud.octofox.de/s/upload

**Comment by GenerationFallout** [comment]
Hello,

I just sent you the logs :)

Kims

**Comment by GenerationFallout** [comment]
Hello,

I take the liberty of bringing up the ticket :) 

Sincerely,

Kims
