### ISSUE TITLE
Incorrect content-type for WebP requests

### ISSUE THREAD

**Issue by alistair3149** [octfx/mediawiki-extension-WebP#8]
**Expected result:**
WebP requests should have `image/webp` as content type.

**Actual result:**
WebP requests have `application/x-wiki` as content type.

![image](https://user-images.githubusercontent.com/9260542/167064011-d96d5568-00b4-4e4f-8659-8ca25baab6c6.png)
![image](https://user-images.githubusercontent.com/9260542/167064043-0551b6c1-b827-4825-8362-d94200a79073.png)

**Comment by octfx** [comment]
Fixed in recent commit
